# Generated by Django 6.0.1 on 2026-01-27 21:54

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_alter', models.CharField(blank=True, max_length=255, verbose_name='Альтернативное название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('format', models.CharField(choices=[('tv', 'TV'), ('ova', 'OVA'), ('ona', 'ONA'), ('movie', 'Фильм'), ('series', 'Сериал'), ('special', 'Спец. выпуск')], default='ona', max_length=20, verbose_name='Формат')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('release_season', models.CharField(blank=True, choices=[('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима')], max_length=10, verbose_name='Сезон выхода')),
                ('status', models.CharField(blank=True, choices=[('announced', 'Анонсировано'), ('ongoing', 'Выходит'), ('completed', 'Завершено'), ('hiatus', 'Пауза')], max_length=15, verbose_name='Статус')),
                ('publish_status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('hidden', 'Скрыто')], default='draft', max_length=10, verbose_name='Статус публикации')),
                ('age_rating', models.CharField(default='0+', max_length=10, verbose_name='Возрастной рейтинг')),
                ('studio', models.CharField(blank=True, max_length=255, verbose_name='Студия')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='anime/images/posters/', verbose_name='Постер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('genres', models.ManyToManyField(blank=True, related_name='anime', to='anime.genre', verbose_name='Жанры')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер серии')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название серии')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime', verbose_name='Аниме')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('anime', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['title'], name='anime_title_idx'),
        ),
    ]
