# Generated by Django 6.0.1 on 2026-01-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release_season',
            field=models.CharField(choices=[('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима')], max_length=10, verbose_name='Сезон выхода'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Год выхода'),
        ),
    ]
