# Generated by Django 6.0.1 on 2026-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_release_season_alter_anime_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
    ]
