# Generated by Django 6.0.1 on 2026-01-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_studio_remove_anime_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='anime.studio', verbose_name='Студия'),
            preserve_default=False,
        ),
    ]
