# Generated by Django 6.0.1 on 2026-01-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime', to='anime.studio', verbose_name='Студия'),
        ),
    ]
