# Generated by Django 6.0.1 on 2026-01-29 15:02

import apps.anime.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_anime_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Still',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.anime.models.still_upload_path, verbose_name='Кадр')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stills', to='anime.anime', verbose_name='Аниме')),
            ],
        ),
    ]
