# Generated by Django 6.0.1 on 2026-02-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_still'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-created_at'], 'verbose_name': 'Anime', 'verbose_name_plural': 'Anime'},
        ),
    ]
