# Generated by Django 6.0.1 on 2026-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_anime_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['publish_status'], name='anime_publish_status_idx'),
        ),
    ]
