# Generated by Django 6.0.1 on 2026-02-07 21:44

import apps.anime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_anime_anime_publish_status_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='still',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.anime.models.still_upload_path, verbose_name='Кадр'),
        ),
    ]
