# Generated by Django 6.0.1 on 2026-02-08 20:01

import apps.anime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_still_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='still',
            options={'verbose_name': 'Still', 'verbose_name_plural': 'Stills'},
        ),
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.FileField(blank=True, upload_to=apps.anime.models.episode_upload_path, verbose_name='Видео'),
        ),
    ]
