# Generated by Django 6.0.1 on 2026-02-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_alter_genre_options_alter_still_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название студии')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='video',
        ),
        migrations.CreateModel(
            name='EpisodeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='anime.episode', verbose_name='Эпизод')),
            ],
        ),
    ]
