# Generated by Django 6.0.1 on 2026-02-09 14:30

import apps.anime.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_voicestudio_remove_episode_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.anime.models.episode_upload_path, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='episodevideo',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to='anime.voicestudio', verbose_name='Озвучка'),
        ),
    ]
