# Generated by Django 6.0.1 on 2026-02-09 14:30

import apps.anime.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_episodevideo_video_episodevideo_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodevideo',
            name='video',
            field=models.FileField(null=True, upload_to=apps.anime.models.episode_upload_path, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='episodevideo',
            name='voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to='anime.voicestudio', verbose_name='Озвучка'),
        ),
    ]
