# Generated by Django 6.0.1 on 2026-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_alter_anime_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='age_rating',
            field=models.IntegerField(choices=[(1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, 'R-17'), (5, 'R-18')], max_length=1, verbose_name='Возрастной рейтинг'),
        ),
    ]
