# Generated by Django 6.0.1 on 2026-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_alter_anime_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(choices=[('g', 'G'), ('pg', 'PG'), ('pg13', 'PG-13'), ('r17', 'R-17'), ('r18', 'R-18')], max_length=10, verbose_name='Возрастной рейтинг'),
        ),
    ]
